[ENH] Update pipeline config layout
nipoppy/nipoppy pull request #383
Opened 2024-10-01 16:57 UTC by michellewang

- Closes #380

Changes proposed in this pull request:
- Rename `proc` -> `pipelines` (not sure that is the best name)
- Change how files are named and stored (everything related to the same pipeline is in the same directory instead of distributed across `invocations`/`descriptors`/other directories

## Checklist (for reviewers)
_This section is for the PR reviewer_

- [ ] PR has an interpretable title with a prefix (e.g. `[BUG]`, `[DOC]`, `[ENH]`, `[MAINT]`)\
Refer to [NumPy Development Guide](https://numpy.org/doc/stable/dev/development_workflow.html#writing-the-commit-message) for a full list
- [ ] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions

2024-10-03 17:14 UTC, mathdugre requested changes

2024-10-03 17:14 UTC, mathdugre commented on nipoppy/data/examples/sample_pipelines/bidscoin-4.3.2/descriptor-bidscoiner.json
We might want to name the descriptor using the step name. This way it would be easier to see which descriptor is associated with invocation and tracker config for a specific step.
note: that if you use the default `descriptor.json`, this can be omitted.

What do you think @michellewang ?

2024-10-03 17:16 UTC, mathdugre approved these changes

2024-10-04 19:43 UTC, michellewang commented on nipoppy/data/examples/sample_pipelines/bidscoin-4.3.2/descriptor-bidscoiner.json
@nikhil153 do you think it would make sense to have the step name be the name of the tool to run for BIDScoin and dcm2bids? For example
- `nipoppy bidsify <DATASET_ROOT> --pipeline bidscoin --pipeline-step bidsmapper`
- `nipoppy bidsify <DATASET_ROOT> --pipeline bidscoin --pipeline-step bidseditor`
- `nipoppy bidsify <DATASET_ROOT> --pipeline bidscoin --pipeline-step bidscoiner`
- `nipoppy bidsify <DATASET_ROOT> --pipeline dcm2bids --pipeline-step dcm2bids_helper`
- `nipoppy bidsify <DATASET_ROOT> --pipeline dcm2bids --pipeline-step dcm2bids` --> this one is kind of weird

The benefit is that we would be more explicit in communicating what is actually being run by the user.

The other option is to rename the descriptors from e.g. `descriptor-bidsmapper.json` to `descriptor-prepare.json`

2024-10-07 20:42 UTC, nikhil153 commented on nipoppy/data/examples/sample_pipelines/bidscoin-4.3.2/descriptor-bidscoiner.json
I don't think this will work a generic case. Most processing pipeline "variants" will not have well defined / unique tool associated with it. So it will get confusing as we still refer to them as steps.

2024-10-07 20:54 UTC, michellewang commented on nipoppy/data/examples/sample_pipelines/bidscoin-4.3.2/descriptor-bidscoiner.json
Ok, so I will merge this and we can see later when implementing the pipeline catalog if we want to do things differently

2024-10-07 20:54 UTC, merged