[ENH] Add dcm2bids 3.2.0
nipoppy/nipoppy pull request #436
Opened 2024-11-22 22:50 UTC by michellewang

- Closes none

Changes proposed in this pull request:
- The container for `dcm2bids` 3.1.0 has a `dcm2niix` binary that was not compiled with the option to handle JPEG-compressed DICOM files, so it doesn't work with DICOMs that have been compressed this way. The container for the latest version of `dcm2bids` (3.2.0) works.

## Checklist (for reviewers)
_This section is for the PR reviewer_

- [ ] PR has an interpretable title with a prefix (e.g. `[BUG]`, `[DOC]`, `[ENH]`, `[MAINT]`)\
Refer to [NumPy Development Guide](https://numpy.org/doc/stable/dev/development_workflow.html#writing-the-commit-message) for a full list
- [ ] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions

2025-02-12 16:13 UTC, mathdugre requested changes

2025-02-12 16:13 UTC, mathdugre commented on nipoppy/data/examples/sample_pipelines/dcm2bids-3.2.0/descriptor-dcm2bids.json
> +    "command-line": "[[NIPOPPY_CONTAINER_COMMAND]] [[NIPOPPY_FPATH_CONTAINER]] [DICOM_DIR] [PARTICIPANT] [SESSION] [CONFIG] [OUTPUT_DIR] [AUTO_EXTRACT_ENTITIES] [DO_NOT_REORDER_ENTITIES] [BIDS_VALIDA
The `dcm2bids` command seems to be missing here

2025-02-12 16:13 UTC, mathdugre commented on nipoppy/data/examples/sample_pipelines/dcm2bids-3.2.0/descriptor-dcm2bids.json
> +            "type": "String",
I think this could use the "File" type, but "String" should be fine as well

2025-02-12 21:56 UTC, michellewang commented on nipoppy/data/examples/sample_pipelines/dcm2bids-3.2.0/descriptor-dcm2bids.json
> +    "command-line": "[[NIPOPPY_CONTAINER_COMMAND]] [[NIPOPPY_FPATH_CONTAINER]] [DICOM_DIR] [PARTICIPANT] [SESSION] [CONFIG] [OUTPUT_DIR] [AUTO_EXTRACT_ENTITIES] [DO_NOT_REORDER_ENTITIES] [BIDS_VALIDA
Because Nipoppy uses `apptainer run` (not `apptainer exec`) by default we don't need the `dcm2bids` command in the command-line

2025-02-20 20:52 UTC, mathdugre approved these changes

2025-02-20 21:13 UTC, merged